//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace CodeSmells.Web.Posts {
    
    
    public partial class GetPosts {
        
        /// <summary>
<<<<<<< HEAD
        /// GetAllPostsGridView control.
=======
        /// CategoriesList control.
>>>>>>> 7b54a55775373e95e1469b78b481cc8423928bee
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
<<<<<<< HEAD
        protected global::System.Web.UI.WebControls.GridView GetAllPostsGridView;
=======
        protected global::System.Web.UI.HtmlControls.HtmlGenericControl CategoriesList;
>>>>>>> 7b54a55775373e95e1469b78b481cc8423928bee
    }
}
